# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirestoreApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirestoreApp

  # Google FireBase Pods

  #pod 'Firebase/Analytics'
  #pod 'Firebase/Database'
  #pod 'Firebase/Core'
  #pod 'Firebase/Firestore'
  #pod 'Firebase/Storage'
  #pod 'Firebase/Analytics'

  target 'FirestoreAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirestoreAppUITests' do
    # Pods for testing
  end

end
